name: Deployment pipeline

on:
  # schedule:
  #  - cron: "0 18 * * *"
  push:
    branches:
      - master
  pull_request:
    branches: [master] # workflow will trigger when someone makes a pull request to the 'master' branch
    types: [opened, synchronize]

jobs:
    deployment_pipeline:
        runs-on: ubuntu-20.04

        services:
          mongo:
            image: mongo:latest
            ports:
              - 27017:27017
            options: >-
              --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm install

            - name: Run linter
              run: npm run lint

            - name: Run JEST/Supertest integration test suites
              run: |
               echo "Starting test server"
               npm run test
              env:
                MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
                SECRET: ${{ secrets.SECRET }}

            - name: Install front-end dependencies
              working-directory: ./UI-frontend
              run: npm install

            - name: Build out the front-end
              working-directory: ./UI-frontend
              run: npm run build

            - name: Move front-end build to backend
              run: |
               rm -rf ./dist
               mv ./UI-frontend/dist ./

            - name: Start the backend testing server
              run: |
                npm run start:test &
                sleep 10

            - name: End-to-end tests using Cypress
              uses: cypress-io/github-action@v5
              with:
                working-directory: ./UI-frontend
                wait-on: http://localhost:3003
                command: npm run cypress:open