name: Deployment pipeline

on:
  # schedule:
  #  - cron: "0 18 * * *"
  push:
    branches:
      - master
  pull_request:
    branches: [master] # workflow will trigger when someone makes a pull request to the 'master' branch
    types: [opened, synchronize]

jobs:
    deployment_pipeline:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm install

            - name: Run linter
              run: npm run lint

            - name: Start the test server database
              run: npm run start:test &
              env:
                MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
            
            - name: Wait for server to be ready
              run: sleep 10
            
            - name: Run JEST/Supertest Integration test suites
              run: npm run test